[build]
  command = "npm run build:client && npm run build:server"

[build.environment]
  NODE_VERSION = "14" # Укажите версию Node.js, которая необходима для вашего сервера

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3000/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/client/build/index.html"
  status = 200
