name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH and deploy
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_URL: ${{ secrets.SSH_URL }}
      run: |
        mkdir -p ~/.ssh/
        echo "${DEPLOY_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Your deployment commands
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${SSH_URL}  "cd /root/papigo/ && git pull origin main && cd ./client && npm run build && pm2 restart 'papigo-server'"
